### ISSUE TITLE
Force close on Carplay 

### ISSUE THREAD

**Issue by ngochoangimsat** [SpotCompiled/SpotC-Plus-Plus#29] opened 2024-05-31 09:15 UTC
App spotc++ ver 2.1.0 is force close if onpen on Car’s head unit use carplay. Ver 1.1.3 work ok. Please fix

**Comment by yodaluca23** [comment] 2024-07-18 02:25
Try it with the latest release?

**Comment by yodaluca23** [comment] 2024-07-21 05:32
@ngochoangimsat ??

**Comment by ngochoangimsat** [comment] 2024-07-22 01:40
I tried lastest version but problem still there. Force close when open Spotify on Carplay

**Comment by yodaluca23** [comment] 2024-07-22 02:23
What's your environment? What iOS version how are you signing it? Etc

**Comment by ngochoangimsat** [comment] 2024-07-22 05:55
I use iphone 13 promax ios 15.3. I installed via TrollStore 
Only 1.1.3 working with carplay. All of higher versions not work on carplay. App force close when open

**Comment by yodaluca23** [comment] 2024-07-22 06:00
> I use iphone 13 promax ios 15.3. I installed via TrollStore Only 1.1.3 working with carplay. All of higher versions not work on carplay. App force close when open. App working ok when hear music on my phone, it only force close when open on Head unit (carplay)

2.0.0, was a big update switching to EeveeSpotify, and a way newer version of Spotify... Could be either as the problem..

**Comment by ngochoangimsat** [comment] 2024-07-22 06:01
Can you try to test on carplay to see what happen and what can be do?

**Comment by yodaluca23** [comment] 2024-07-22 06:03
> Can you try to test on carplay to see what happen and what can be do?

I don't have a car available to me that's compatible with carplay. Does the NowPlaying API functionality work?

**Comment by ngochoangimsat** [comment] 2024-07-22 06:05
Now playing work, home screen widget can next and preview songs and play/stop ok. Only when press Spotify shortcut then screen show loading for about 1-2s then quit the app

**Comment by yodaluca23** [comment] 2024-07-22 06:08
> Now playing work, home screen widget can next and preview songs and play/stop ok. Only when press Spotify shortcut then screen show loading for about 1-2s then quit the app

Have you tried deleting the app and reinstalling it?

**Comment by yodaluca23** [comment] 2024-07-22 06:16
Wait a minute, if your on 15.3, you can just install Spotify from the appstore, and install the following tweaks (these are what is bundled):

[EeveeSpotify](https://github.com/whoeevee/EeveeSpotify)
[SwiftProtobuf](https://github.com/whoeevee/EeveeSpotify)
[Orion](https://chariz.com/get/orion-runtime14)
[Sposify](https://www.ios-repo-updates.com/repository/dynastic/package/com.spos)
[SposifyFix](https://www.ios-repo-updates.com/repository/level3tjg/package/com.level3tjg.sposifyfix)

**Comment by yodaluca23** [comment] 2024-07-22 06:20
I might've found the problem give me a second

**Comment by ngochoangimsat** [comment] 2024-07-22 06:21
I am on none jaibreak device, use trollstore method. It seam can not install Orion

**Comment by yodaluca23** [comment] 2024-07-22 06:38
> I am on none jaibreak device, use trollstore method. It seam can not install Orion

You can jailbreak with Dopamine, Orion is on the chariz repo, make sure its added.

**Comment by ngochoangimsat** [comment] 2024-07-22 06:41
My phone will not jaibreak for seccurity from bank app require.

**Comment by yodaluca23** [comment] 2024-07-22 06:51
Try this ipa https://litter.catbox.moe/net99b.ipa

**Comment by ngochoangimsat** [comment] 2024-07-22 06:59
![405FCBE0-5827-48C9-BB25-F6EE7D63A02A](https://github.com/user-attachments/assets/e7630130-63ca-4001-a3d4-0a1b74c2cd3d)
This app working fine! Thank you so much!

**Comment by yodaluca23** [comment] 2024-07-22 07:02
> This app working fine! Thank you so much!

Ok then the problem is the bundle ID I change it so that It can work with sidestore/altstore which requires a unique bundle ID per app. It looks like I'll be making two versions from now on one with an unmodified ID and one with it modified which I'll use in the source. You can use that for now. It'll probably take me a while to get this set up with the script. I'll close this when I get that working, I'll do that tomorrow.

**Comment by ngochoangimsat** [comment] 2024-07-22 07:05
Thank you from Vietnamese!

**Comment by yodaluca23** [comment] 2024-07-22 20:58
I updated the release script, to include two .ipa's and two repos one with the BundleID changed to work with AltStore/SideStore, and one with it unchanged for everything else (this one will work with carplay, it doesn't matter that the AltStore one won't work, because personal dev certs don't support carplay anyways), also used in the new Scarlet repo.

**Closed** 2024-07-22 20:58 UTC

**Comment by yodaluca23** [comment] 2024-07-29 23:18
@ngochoangimsat Can you just verify for me that the latest release works properly?

**Comment by wangdefa8** [comment] 2024-10-06 14:51
> @ngochoangimsat Can you just verify for me that the latest release works properly?

The 2.2.9 version of carplay does not work, and it is installed in ios18 using altstore.

**Comment by yodaluca23** [comment] 2024-10-06 15:39
> The 2.2.9 version of carplay does not work, and it is installed in ios18 using altstore.

AltStore with a free dev certificate will not have the needed entitlements..

**Comment by ngochoangimsat** [comment] 2024-10-10 04:23
I came back to 1.1. 2.x almost have problem with carplay. Your fixed version work but most of time i have to open spotify on my phone first then i can use able on head unit. otherwise still force stop problem

**Comment by ngochoangimsat** [comment] 2024-10-10 04:28
I will test 2.3.1 and feedbacks soon

**Comment by ngochoangimsat** [comment] 2024-10-10 04:43
I tested latest version, some time fore close some time work. I still back to 1.1.3

**Comment by yodaluca23** [comment] 2024-10-10 14:05
> I tested latest version, some time fore close some time work. I still back to 1.1.3

I suggest trying https://github.com/SpotCompiled/SpotveeC the extra tweaks might have some conflicts with the CarPlay app...
