### ISSUE TITLE
Doesnt work on apple carplay

### ISSUE THREAD

**Issue by Asetia4116** [SpotCompiled/SpotC-Plus-Plus#39] opened 2024-07-21 00:48 UTC
The app doesn't show on apple carplay and glitches when i try to listen to music

**Comment by yodaluca23** [comment] 2024-07-21 05:33
It requires TrollStore for CarPlay. It should work with the NowPlaying API though...

**Comment by yodaluca23** [comment] 2024-07-22 07:02
Duplicate of #29

**Closed by yodaluca23** 2024-07-22 07:02 UTC
